@api = http://localhost:4000/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "username": "ucamp",
    "password": "121212"
}

### sign up
POST {{api}}
Content-Type: application/json

{
    "email": "jesus@correo.com",
    "username": "jesus",
    "password": "121212"
}

### renovar token
{{api}}
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzI1MDIyZDViZWNjODY4YzgxNzVlMyIsImlhdCI6MTY2NDI0MTcxOCwiZXhwIjoxNjY0MjU2MTE4fQ.cNNwStnvndcce4vjiuWM5F9ZLq7bvL2NhE_5fw5dINc